import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Water} from 'three/addons/objects/Water.js';
const $=s=>document.querySelector(s), canvas=$('#world'),stage=$('.scene-viewport');
const state={location:'exterior',preset:'moon',smoke:true,waves:true,rotate:false,exposure:100,fog:20,volume:35,quality:'balanced',flying:false,tour:false,audio:false};
const scenes=new Map(),loader=new GLTFLoader();let renderer,scene,camera,orbit,env,model,loadId=0,lastTime=0,elapsed=0,tourStart=0;const keys=new Set();const tmp=new THREE.Vector3();let yaw=0,pitch=0,dragging=false,lastPointer=[0,0];
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('#error').hidden=false;$('#errorText').textContent='当前浏览器没有启用三维图形加速，请使用较新的 Chrome 或 Edge 并启用硬件加速。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.outputColorSpace=THREE.SRGBColorSpace;
scene=new THREE.Scene();scene.background=new THREE.Color('#0b202f');scene.fog=new THREE.FogExp2('#0b202f',.0012);
camera=new THREE.PerspectiveCamera(42,1,.15,18000);camera.position.set(240,90,340);
orbit=new OrbitControls(camera,canvas);orbit.target.set(0,18,0);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.minDistance=4;orbit.maxDistance=850;orbit.maxPolarAngle=Math.PI*.485;
const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();env=pmrem.fromScene(room,.04).texture;room.dispose();scene.environment=env;scene.environmentIntensity=.45;
const ambient=new THREE.HemisphereLight(0x9ccdf5,0x0b1420,1.2);scene.add(ambient);
const sun=new THREE.DirectionalLight(0x83b7ff,2.3);sun.position.set(-100,200,150);scene.add(sun);
const fill=new THREE.DirectionalLight(0xffd398,1.1);fill.position.set(0,80,80);scene.add(fill);
const normalSize=128,normalPixels=new Uint8Array(normalSize*normalSize*4);for(let y=0;y<normalSize;y++)for(let x=0;x<normalSize;x++){const u=x/normalSize*Math.PI*2,v=y/normalSize*Math.PI*2,i=(y*normalSize+x)*4;const dx=.5*Math.cos(5*u+3*v)+.26*Math.cos(13*u-7*v)+.18*Math.cos(23*u+17*v),dy=.4*Math.cos(5*u+3*v)-.25*Math.cos(13*u-7*v)+.21*Math.cos(23*u+17*v);normalPixels[i]=128+dx*90;normalPixels[i+1]=128+dy*90;normalPixels[i+2]=220;normalPixels[i+3]=255;}
const normalTexture=new THREE.DataTexture(normalPixels,normalSize,normalSize);normalTexture.wrapS=normalTexture.wrapT=THREE.RepeatWrapping;normalTexture.magFilter=normalTexture.minFilter=THREE.LinearFilter;normalTexture.needsUpdate=true;
const water=new Water(new THREE.PlaneGeometry(14000,14000),{textureWidth:512,textureHeight:512,waterNormals:normalTexture,sunDirection:new THREE.Vector3(-.5,1,.4).normalize(),sunColor:0x98bfff,waterColor:0x082a3b,distortionScale:2.1,fog:true});water.rotation.x=-Math.PI/2;water.position.y=-.45;water.material.uniforms.size.value=3.2;scene.add(water);
const moon=new THREE.Mesh(new THREE.SphereGeometry(19,24,16),new THREE.MeshBasicMaterial({color:0xe3efff}));moon.position.set(-270,340,-1300);scene.add(moon);
const sky=new THREE.Mesh(new THREE.SphereGeometry(8500,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#081322')},bottom:{value:new THREE.Color('#234451')}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vP;void main(){float h=clamp(normalize(vP).y*2.,0.,1.);gl_FragColor=vec4(mix(bottom,top,pow(h,.65)),1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));scene.add(sky);
// A finite particle field keeps the smoke inexpensive enough for free navigation.
const particleCount=150,particles=new THREE.BufferGeometry(),positions=new Float32Array(particleCount*3),sizes=new Float32Array(particleCount),alphas=new Float32Array(particleCount);particles.setAttribute('position',new THREE.BufferAttribute(positions,3));particles.setAttribute('size',new THREE.BufferAttribute(sizes,1));particles.setAttribute('opacity',new THREE.BufferAttribute(alphas,1));
const smokeMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{tint:{value:new THREE.Color('#77818d')},screenHeight:{value:720}},vertexShader:'attribute float size;attribute float opacity;varying float a;uniform float screenHeight;void main(){vec4 p=modelViewMatrix*vec4(position,1.);a=opacity;gl_PointSize=clamp(size*screenHeight/max(1.,-p.z),1.,220.);gl_Position=projectionMatrix*p;}',fragmentShader:'varying float a;uniform vec3 tint;void main(){vec2 p=gl_PointCoord*2.-1.;float r=length(p);float noise=.75+.25*sin(p.x*13.+sin(p.y*9.))*cos(p.y*11.);float alpha=(1.-smoothstep(.12,1.,r))*noise*a;if(alpha<.008)discard;gl_FragColor=vec4(tint,alpha);}' });const smokeCloud=new THREE.Points(particles,smokeMaterial);smokeCloud.frustumCulled=false;scene.add(smokeCloud);
const starsGeo=new THREE.BufferGeometry(),starData=[];for(let i=0;i<500;i++){const a=i*2.39996,y=300+((i*137)%1800),r=2400;starData.push(Math.cos(a)*r,y,Math.sin(a)*r);}starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(starData,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xd9e9ff,size:1.5,transparent:true,opacity:.65,depthWrite:false}));scene.add(stars);
const interiorLights=new THREE.Group();scene.add(interiorLights);
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.zoom=window.innerWidth<=760&&isExterior()?.8:1;camera.updateProjectionMatrix();smokeMaterial.uniforms.screenHeight.value=h*renderer.getPixelRatio();}new ResizeObserver(resize).observe(stage);resize();
function isExterior(){return ['exterior','bow'].includes(state.location);}
async function loadLocation(key,{keepTour=false}={}){if(!locations[key])throw new Error('无效的探索地点');if(!keepTour)stopTour();setFlying(false);const name=key==='bow'?'exterior':key,id=++loadId;$('#loadStatus').hidden=false;$('#error').hidden=true;try{if(!scenes.has(name)){const gltf=await loader.loadAsync('./assets/'+name+'.glb');gltf.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material.envMapIntensity=.45;if(o.material.emissiveIntensity>0)o.material.emissiveIntensity=Math.min(o.material.emissiveIntensity,2);}}});scenes.set(name,gltf.scene);}if(id!==loadId)return;if(model)scene.remove(model);model=scenes.get(name);scene.add(model);state.location=key;const exterior=name==='exterior';water.visible=sky.visible=exterior;const loc=locations[key];camera.fov=exterior?42:65;camera.updateProjectionMatrix();camera.position.fromArray(loc.pos);orbit.target.fromArray(loc.target);orbit.maxPolarAngle=exterior?Math.PI*.49:Math.PI;orbit.minDistance=exterior?3:.15;orbit.maxDistance=exterior?850:30;$('#sceneTitle').textContent=loc.title;$('#shipChineseName').hidden=loc.title!=='TITANIC';$('#memoryQuote').hidden=key!=='exterior';$('#sceneSubtitle').textContent=loc.sub;$('#sceneDescription').innerHTML=loc.desc;$('#viewName').textContent=loc.sub;$('.heading').classList.toggle('interior',!exterior);document.querySelectorAll('[data-location]').forEach(b=>{b.classList.toggle('selected',b.dataset.location===key);b.setAttribute('aria-pressed',String(b.dataset.location===key));});$('#locationCaption').textContent=exterior?'41°43′ N · 49°56′ W  · 北大西洋氛围场景':'TITANIC · '+loc.sub+' · 独立室内空间';$('#tourButton').disabled=!exterior;interiorLights.clear();if(!exterior){const lamps=name==='staircase'?[[0,7.8,1],[-5,7.8,-5],[5,7.8,-5]]:name==='suite'?[[0,3.1,0]]:[[0,4.2,6],[0,4.2,-1],[0,4.2,-8]];lamps.forEach(p=>{const l=new THREE.PointLight(0xffc17d,name==='suite'?90:230,35,1.6);l.position.fromArray(p);interiorLights.add(l);});}
resize();applyLighting(state.preset);$('#loadStatus').hidden=true;orbit.update();window.dispatchEvent(new CustomEvent('titanic:location',{detail:{location:key}}));return readState();}catch(e){if(id===loadId){$('#loadStatus').hidden=true;$('#error').hidden=false;$('#errorText').textContent='场景资源暂时无法载入。请检查网络后重新尝试。';}throw e;}}
const locations={exterior:{title:'TITANIC',sub:'北大西洋之夜',desc:'月色落在海面，<br>灯火沿着巨轮缓缓延伸。',pos:[240,90,340],target:[0,18,0]},bow:{title:'THE BOW',sub:'船首甲板',desc:'站在巨轮的前沿，<br>望向无边的北大西洋。',pos:[145,17,27],target:[72,23,0]},staircase:{title:'GRAND STAIRCASE',sub:'豪华大阶梯',desc:'橡木、黄铜与穹顶，<br>重访一段温暖的旧日时光。',pos:[0,2.4,10],target:[0,4.6,-5]},suite:{title:'FIRST CLASS',sub:'头等舱套房',desc:'舷窗外是海，<br>房间里是安静的夜晚。',pos:[3.8,2.5,5.4],target:[-.2,1.7,-1.7]},dining:{title:'DINING SALOON',sub:'烛光餐厅',desc:'晚宴尚未散去，<br>光在瓷器与银器间流动。',pos:[7,2.9,10.8],target:[-1,2.6,-3]}};
document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>loadLocation(b.dataset.location).catch(console.error));
const presets={moon:{label:'MOONLIGHT',bg:'#0b202f',top:'#061221',bottom:'#294c5c',sun:'#8bbcff',sunPower:2.1,ambient:1.05,fill:.8,env:.38,water:0x082939,smoke:'#8497a6',position:[-100,200,150]},sunset:{label:'GOLDEN HOUR',bg:'#706166',top:'#24344c',bottom:'#b99578',sun:'#ffc48e',sunPower:3.7,ambient:1.9,fill:1.1,env:.75,water:0x344b51,smoke:'#444550',position:[-180,65,-170]},day:{label:'DAYLIGHT',bg:'#a9c5cf',top:'#537e9d',bottom:'#bbcbd0',sun:'#fff0d7',sunPower:3.4,ambient:2.5,fill:1.5,env:1,water:0x155c71,smoke:'#455363',position:[120,210,40]}};
const exteriorDescriptions={day:'阳光洒向海面，<br>巨轮驶向辽阔的远方。',sunset:'余晖染亮海面，<br>巨轮缓缓驶入金色黄昏。',moon:'月色落在海面，<br>灯火沿着巨轮缓缓延伸。'};
function applyLighting(name){if(!presets[name])throw new Error('无效的光线预设');if(state.location==='exterior')$('#sceneDescription').innerHTML=exteriorDescriptions[name];state.preset=name;const p=presets[name],ext=isExterior();scene.background=new THREE.Color(ext?p.bg:'#24180e');scene.fog=ext?new THREE.FogExp2(p.bg,.00022+state.fog*.000047):null;sun.color.set(ext?p.sun:'#ffdb9e');sun.intensity=ext?p.sunPower:1.4;sun.position.fromArray(p.position);ambient.intensity=ext?p.ambient:1.4;ambient.color.set(ext?p.sun:'#ffd4a0');ambient.groundColor.set(ext?'#122735':'#694827');fill.intensity=ext?p.fill:.4;scene.environmentIntensity=ext?p.env:.6;water.material.uniforms.sunColor.value.set(p.sun);water.material.uniforms.waterColor.value.set(p.water);water.material.uniforms.sunDirection.value.copy(sun.position).normalize();sky.material.uniforms.top.value.set(p.top);sky.material.uniforms.bottom.value.set(p.bottom);moon.visible=stars.visible=ext&&name==='moon';smokeCloud.visible=ext&&state.smoke;smokeMaterial.uniforms.tint.value.set(p.smoke);renderer.toneMappingExposure=state.exposure/100*(ext?1.0:1.15);$('#lightLabel').textContent=p.label;document.querySelectorAll('[data-preset]').forEach(b=>{b.classList.toggle('active',b.dataset.preset===name);b.setAttribute('aria-pressed',String(b.dataset.preset===name));});return readState();}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyLighting(b.dataset.preset));
for(const id of ['exposure','fog','volume'])$('#'+id).addEventListener('input',e=>{state[id]=Number(e.target.value);$('#'+id+'Value').value=state[id]+'%';if(id==='volume'){audio.volume=state.volume/100;}else applyLighting(state.preset);});
for(const id of ['smoke','waves','rotate'])$('#'+id).addEventListener('change',e=>{state[id]=e.target.checked;if(id==='smoke')smokeCloud.visible=isExterior()&&state.smoke;if(id==='rotate'&&state.rotate){stopTour();setFlying(false);}orbit.autoRotate=state.rotate&&isExterior();});
function setQuality(q){if(!['low','balanced','high'].includes(q))throw new Error('无效的画质选项');state.quality=q;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?2:q==='low'?1:1.5));smokeCloud.geometry.setDrawRange(0,q==='low'?75:particleCount);resize();}
$('#quality').onchange=e=>setQuality(e.target.value);
const audio=new Audio('./assets/atlantic.wav');audio.loop=true;audio.volume=.35;audio.preload='none';
async function toggleAudio(){if(state.audio){audio.pause();state.audio=false;}else{try{await audio.play();state.audio=true;}catch(e){$('#soundNote').textContent='音频暂时没有播放，请再次点击“开启环境声音”。';return;}}$('#audioButton').setAttribute('aria-pressed',String(state.audio));$('#audioButton span').textContent=state.audio?'关闭环境声音':'开启环境声音';$('#soundNote').textContent=state.audio?'海浪 · 低沉轮机 · 远处的风':'点击上方“开启环境声音”，听见海浪与轮机。';}
$('#audioButton').onclick=toggleAudio;audio.addEventListener('error',()=>{$('#soundNote').textContent='声音加载失败，请稍后重试。';state.audio=false;$('#audioButton').setAttribute('aria-pressed','false');$('#audioButton span').textContent='开启环境声音';});
function setFlying(value){state.flying=value;keys.clear();dragging=false;orbit.enabled=!value;if(value){camera.getWorldDirection(tmp);yaw=Math.atan2(-tmp.x,-tmp.z);pitch=Math.asin(THREE.MathUtils.clamp(tmp.y,-1,1));state.rotate=false;$('#rotate').checked=false;orbit.autoRotate=false;stopTour();canvas.focus();}else{camera.getWorldDirection(tmp);orbit.target.copy(camera.position).addScaledVector(tmp,isExterior()?35:3);orbit.update();}$('#flyButton').setAttribute('aria-pressed',String(value));$('#flyButton').textContent=value?'⌖ 退出漫游':'⌖ 自由漫游';$('#flyPad').hidden=!value;$('#navigationTip').textContent=value?'WASD 移动 · Q/E 升降 · 拖动转向 · Esc 退出':'拖动旋转 · 滚轮缩放 · 右键平移';}
$('#flyButton').onclick=()=>setFlying(!state.flying);
canvas.addEventListener('pointerdown',e=>{if(!state.flying)return;dragging=true;lastPointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!state.flying||!dragging)return;yaw-=(e.clientX-lastPointer[0])*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lastPointer[1])*.004,-1.48,1.48);lastPointer=[e.clientX,e.clientY];});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
document.addEventListener('keydown',e=>{if($('#story').open||$('#archive').open)return;if(e.key==='Escape'){stopTour();if(state.flying)setFlying(false);$('#settings').classList.remove('open');}if(!state.flying||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('#help').open)return;if(['w','a','s','d','q','e','shift','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){keys.add(e.key.toLowerCase());e.preventDefault();}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();dragging=false;});
const moveMap={up:'w',down:'s',left:'a',right:'d',rise:'e',fall:'q'};document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{keys.add(moveMap[b.dataset.move]);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(moveMap[b.dataset.move]);});
function stopTour(){if(!state.tour)return;state.tour=false;orbit.enabled=!state.flying;$('#tourButton').setAttribute('aria-pressed','false');$('#tourButton').textContent='▷ 25 秒巡航';$('#tourProgress').hidden=true;camera.getWorldDirection(tmp);orbit.target.copy(camera.position).addScaledVector(tmp,100);camera.fov=42;camera.updateProjectionMatrix();}
async function startTour(){if(state.tour){stopTour();return;}if(!isExterior())await loadLocation('exterior');setFlying(false);state.rotate=false;$('#rotate').checked=false;orbit.autoRotate=false;state.tour=true;orbit.enabled=false;tourStart=elapsed;$('#tourButton').setAttribute('aria-pressed','true');$('#tourButton').textContent='Ⅱ 结束巡航';$('#tourProgress').hidden=false;}
$('#tourButton').onclick=startTour;$('#resetButton').onclick=()=>{stopTour();loadLocation(state.location).catch(console.error);};
$('#helpButton').onclick=()=>$('#help').showModal();$('#helpDone').onclick=$('#helpClose').onclick=()=>$('#help').close();$('#settingsToggle').onclick=()=>{$('#settings').classList.toggle('open');$('#settingsToggle').setAttribute('aria-expanded',String($('#settings').classList.contains('open')));};let expanded=false,fullBusy=false,previousScroll=0;
function setExpanded(value){expanded=value;document.body.classList.toggle('scene-expanded',value);$('#exitSceneFull').hidden=!value;$('#fullButton').setAttribute('aria-pressed',String(value));if(value){previousScroll=window.scrollY;$('#exitSceneFull').focus({preventScroll:true});}else{window.scrollTo(0,previousScroll);$('#fullButton').focus({preventScroll:true});}requestAnimationFrame(resize);}
async function exitSceneFull(){if(fullBusy)return;fullBusy=true;try{if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen();}catch(e){}finally{setExpanded(false);fullBusy=false;}}
$('#fullButton').onclick=async()=>{if(fullBusy)return;if(expanded){await exitSceneFull();return;}setExpanded(true);if(document.fullscreenEnabled&&document.documentElement.requestFullscreen){fullBusy=true;try{await document.documentElement.requestFullscreen();}catch(e){/* Keep the usable in-page expanded view when native fullscreen is denied. */}finally{fullBusy=false;}}};
$('#exitSceneFull').onclick=exitSceneFull;
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&expanded)setExpanded(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&expanded)exitSceneFull();});

function readState(){return {...state,position:camera.position.toArray().map(n=>Math.round(n*100)/100),loadedLocations:[...scenes.keys()]};}
function updateTour(t){let a,b,ta,tb,u,fov;if(t<8){u=t/8;a=[177,5.5,77];b=[151,10.5,44];ta=[103,17,0];tb=[78,23,0];fov=54;}else if(t<17){u=(t-8)/9;a=[111,16,61];b=[-75,24,64];ta=[61,22,0];tb=[-29,27,0];fov=49;}else{u=Math.min(1,(t-17)/8);a=[-151,53,184];b=[-230,121,350];ta=[-5,21,-8];tb=[5,19,-17];fov=42;}camera.position.fromArray(a).lerp(new THREE.Vector3(...b),u);camera.lookAt(new THREE.Vector3(...ta).lerp(new THREE.Vector3(...tb),u));camera.fov=fov;camera.updateProjectionMatrix();$('#tourProgress span').style.width=Math.min(100,t/25*100)+'%';if(t>=25)stopTour();}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-lastTime)/1000||0,.06);lastTime=now;elapsed+=dt;if(state.waves)water.material.uniforms.time.value+=dt*.42;if(state.smoke&&isExterior()){for(let i=0;i<particleCount;i++){const f=Math.floor(i/50),age=((i%50)/50+elapsed*.053)%1,seed=i*1.736;positions[i*3]=[51,16,-19][f]-2.7-age*43+Math.sin(seed+age*9)*age*3;positions[i*3+1]=40+age*18+Math.sin(seed*.7)*age*2;positions[i*3+2]=-age*5+Math.sin(seed)*age*4;sizes[i]=3.5+age*12;alphas[i]=Math.sin(Math.PI*age)*.22;}particles.attributes.position.needsUpdate=particles.attributes.size.needsUpdate=particles.attributes.opacity.needsUpdate=true;}
if(state.tour)updateTour(elapsed-tourStart);else if(state.flying){camera.rotation.set(pitch,yaw,0,'YXZ');const speed=dt*(isExterior()?16:2.2)*(keys.has('shift')?3:1);camera.getWorldDirection(tmp);if(keys.has('w')||keys.has('arrowup'))camera.position.addScaledVector(tmp,speed);if(keys.has('s')||keys.has('arrowdown'))camera.position.addScaledVector(tmp,-speed);tmp.crossVectors(camera.up,tmp).normalize();if(keys.has('a')||keys.has('arrowleft'))camera.position.addScaledVector(tmp,speed);if(keys.has('d')||keys.has('arrowright'))camera.position.addScaledVector(tmp,-speed);if(keys.has('e'))camera.position.y+=speed;if(keys.has('q'))camera.position.y-=speed;if(isExterior())camera.position.y=Math.max(.6,camera.position.y);camera.position.clamp(new THREE.Vector3(-4000,-10,-4000),new THREE.Vector3(4000,1200,4000));}else{orbit.autoRotate=state.rotate&&isExterior();orbit.autoRotateSpeed=.42;orbit.update(dt);}$('#compassNeedle').style.transform=`rotate(${-camera.rotation.y*180/Math.PI}deg)`;renderer.render(scene,camera);}
requestAnimationFrame(animate);await loadLocation('exterior');
// The same public actions power the visible controls and optional agent tools.
const api={getState:readState,visit:loadLocation,lighting:applyLighting,tour:startTour};window.titanic=api;
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=(tool)=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn);}catch(e){console.warn(e);}};
register({name:'titanic_get_state',title:'读取航行状态',description:'Read the current location, lighting, camera mode and loaded scenes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>readState()});
register({name:'titanic_explore',title:'切换探索地点与光线',description:'Navigate to a ship location and optionally select its lighting. Updates the same scene shown to the user.',inputSchema:{type:'object',properties:{location:{type:'string',enum:Object.keys(locations)},lighting:{type:'string',enum:Object.keys(presets)}},required:['location'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||!locations[input.location]||(input.lighting&&!presets[input.lighting]))throw Error('Invalid location or lighting');await loadLocation(input.location);if(input.lighting)applyLighting(input.lighting);return readState();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

const titleSizeObserver=new ResizeObserver(()=>{document.getElementById('shipChineseName').style.width=document.getElementById('sceneTitle').getBoundingClientRect().width+'px';});titleSizeObserver.observe(document.getElementById('sceneTitle'));
